language: python
python:
  - "3.6.6"
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codecov
  - pip install librosa
script:
  - nosetests -v --with-coverage --cover-tests --cover-package=.
after_success:
  - codecov